import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const playwriteGBS = localFont({
  src: "./fonts/PlaywriteGBS-VariableFont_wght.ttf",
  variable: "--font-playwriteGBS",
  weight: "100 900",
});
const pacifico = localFont({
  src: "./fonts/Pacifico-Regular.ttf",
  variable: "--font-pacifico",
  weight: "100 900",
});
const itim = localFont({
  src: "./fonts/Itim-Regular.ttf",
  variable: "--font-itim",
  weight: "100 900",
});
const mitrReg = localFont({
  src: "./fonts/Mitr-Regular.ttf",
  variable: "--font-mitr-reg",
  weight: "100 900",
});
const mitrMedium = localFont({
  src: "./fonts/Mitr-Medium.ttf",
  variable: "--font-mitr-med",
  weight: "100 900",
});

export const metadata = {
  title: "3Y Anv.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${mitrMedium.variable} ${mitrReg.variable} ${pacifico.variable} ${itim.variable} ${playwriteGBS.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
